export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as LoginPage } from './LoginPage'
export { default as SignUpPage } from './SignUpPage'
export { default as PricingPage } from './PricingPage'
export { default as Dashboard } from './Dashboard'
export { default as LoadingPage } from './LoadingPage'
export { default as GeneratedSlides } from './GeneratedSlides'