export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as LoginPage } from './LoginPage'
export { default as SignUpPage } from './SignUpPage'
// export { default as OnboardingPageOne } from './OnboardingPageOne'
// export { default as OnboardingPageTwo } from './OnboardingPageTwo'
// export { default as OnboardingPageThree } from './OnboardingPageThree'
// export { default as OnboardingPageFour } from './OnboardingPageFour'
// export { default as OnboardingPageFive } from './OnboardingPageFive'
export { default as DashboardPageOne } from './DashboardPageOne'
export { default as DownloadOverlayPage } from './DownloadOverlayPage'
export { default as PreviewPage } from './PreviewPage'
export { default as ContentPage } from './ContentPage'
export { default as ContentPastedPage } from './ContentPastedPage'