export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
export { default as Verification } from './Verification'
export { default as Description } from './Description'
export { default as ForgotPassword1 } from './ForgotPassword1'
export { default as ForgotPassword2 } from './ForgotPassword2'
export { default as Navbar } from "./Navbar";
export { default as HeroSection } from "./HeroSection";
export { default as Features } from "./Features";
export { default as Pricing } from "./Pricing";
export { default as Contact } from "./Contact";
export { default as Partners } from "./Partners";
export { default as DashboardNavbar } from "./DashboardNavbar";
export { default as Loading } from "./Loading";
export { default as Footer } from "./Footer";
