export { default as Navbar } from './Navbar'
export { default as HeroSection } from './HeroSection'
export { default as Footer } from './Footer'
export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
export { default as Verification } from './Verification'
export { default as Description } from './Description'
export { default as ForgotPassword1 } from './ForgotPassword1'
export { default as ForgotPassword2 } from './ForgotPassword2'
// export { default as OnboardingOne } from './OnboardingOne'
// export { default as OnboardingTwo } from './OnboardingTwo'
// export { default as OnboardingThree } from './OnboardingThree'
// export { default as OnboardingFour } from './OnboardingFour'
// export { default as OnboardingFive } from './OnboardingFive'
export { default as Dashboard } from './Dashboard'
export { default as SideNav } from './SideNav'
export { default as Presentations } from './Presentations'
export { default as DashboardNavbar } from './DashboardNavbar'
export { default as DownloadOverlay } from './DownloadOverlay'
export { default as DownloadDialogueBox } from './DownloadDialogueBox'
export { default as Preview } from './Preview'
export { default as PreviewNavbar } from './PreviewNavbar'
export { default as PreviewThumbnail } from './PreviewThumbnail'
export { default as PreviewSlide } from './PreviewSlide'